version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STREAMLIT_SERVER_PORT=8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./core:/app/core
      - ./processors:/app/processors
    restart: unless-stopped
